# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by ./build-setup.sh
conda activate /home/tangke/cs152/chipyard/.conda-env
source /home/tangke/cs152/chipyard-cs152-sp23/scripts/fix-open-files.sh
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by build-setup.sh
conda activate /home/tangke/cs152/chipyard/.conda-env
source /home/tangke/cs152/chipyard-cs152-sp23/scripts/fix-open-files.sh
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by ./build-setup.sh
conda activate /home/tangke/cs152/chipyard/.conda-env
source /home/tangke/cs152/chipyard-cs152-sp23/scripts/fix-open-files.sh
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by ./build-setup.sh
conda activate /home/tangke/cs152/chipyard/.conda-env
source /home/tangke/cs152/chipyard-cs152-sp23/scripts/fix-open-files.sh
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by ./build-setup.sh
conda activate /home/tangke/cs152/chipyard/.conda-env
source /home/tangke/cs152/chipyard-cs152-sp23/scripts/fix-open-files.sh
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by ./build-setup.sh
conda activate /home/tangke/cs152/chipyard/.conda-env
source /home/tangke/cs152/chipyard-cs152-sp23/scripts/fix-open-files.sh
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by ./build-setup.sh
conda activate /home/tangke/cs152/chipyard/.conda-env
source /home/tangke/cs152/chipyard-cs152-sp23/scripts/fix-open-files.sh
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by ./build-setup.sh
conda activate /home/tangke/cs152/chipyard/.conda-env
source /home/tangke/cs152/chipyard-cs152-sp23/scripts/fix-open-files.sh
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/tangke/cs152/chipyard-cs152-sp23"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by ./build-setup.sh
conda activate /home/tangke/cs152/chipyard/.conda-env
source /home/tangke/cs152/chipyard-cs152-sp23/scripts/fix-open-files.sh
